### ISSUE TITLE
Committing multiple files

### ISSUE THREAD

**Issue by wnitz** [mmarkeloff/vscode-cvs#2]
Currently there is no way to commit multiple files, the commit command only allows committing the currently opened file.
Is this feature planned?

**Comment by mmarkeloff** [comment]
See "CodeCVS: commit content".

**Comment by wnitz** [comment]
When I run this command it lists all of the modified files in the project, it doesn't let me choose which files to commit.
It also shows all of the files with the unknown status, '?', and files that were update remotely, 'U'.
I don't understand if it will commit these files or not.

**Comment by mmarkeloff** [comment]
Fixed in 0.1.0.

**Comment by wnitz** [comment]
Nice update!
I really like the checkbox design and the link to compare the modified files.
But when I press the link all of the files are being compared one after the other in the same tab, so instead of getting a tab for each modified file I see one tab trying to compare the first, then the title changes to the second, then it changes to the third file.
So there are two issue with it:
1. All of the files are shown when I press the link instead of only the files that I checked.
2. The files are being opened in the same tab so I can't really see all of the modified files.

**Comment by mmarkeloff** [comment]
2. Try to add "workbench.editor.enablePreview": false to your settings.json.

**Comment by wnitz** [comment]
Thanks, this resolved #2

**Comment by mmarkeloff** [comment]
1. Fixed in 0.1.1.

**Comment by wnitz** [comment]
Thanks! Works great now!
