### ISSUE TITLE
Commit message is only limited to one line

### ISSUE THREAD

**Issue by wnitz** [mmarkeloff/vscode-cvs#3]
The commit message is limited to one line, when I try to go down a line using Ctrl+Enter or Shift+Enter it is registered as a regular Enter press and I approved the commit message instead of getting a new line.
VSCode supports this for Git now:
https://code.visualstudio.com/updates/v0_5_0#:~:text=Multiline%20commit,-Previously%2C%20commit%20messages&text=We%20now%20support%20multiple%20lines,new%20line%20to%20the%20message.)

**Comment by mmarkeloff** [comment]
Available in version 0.0.8.
