### ISSUE TITLE
Update repository command

### ISSUE THREAD

**Issue by wnitz** [mmarkeloff/vscode-cvs#5]
Is it possible to add an update command for the repository?
To be able to execute "cvs up -d" on the directory from the GUI

**Comment by wnitz** [comment]
I just noticed that there is an update command, but it doesn't work, I tried it now it shows:
"Unable to update local repository: "
Is there a way to get more information on the problem?

**Comment by mmarkeloff** [comment]
Hi, 

"CodeCVS extension duplicates stderr of the CLI CVS client to the OUTPUT tab. To see CVS errors, select vscode-cvs from the contextual menu."

**Comment by wnitz** [comment]
I executed the command again in the same directory and this time it succeeded.
I found the log you mentioned, so I will have a look on it if it fails.
I'm closing the issue.
