### ISSUE TITLE
Open diff window for a single file from the commit window

### ISSUE THREAD

**Issue by wnitz** [mmarkeloff/vscode-cvs#8]
When I reviewed all of the files for commit but then I want to go back only to a few, I need to find the files and call the compare command.
Instead it would help if there was a way to select a specific file from the commit window and open the diff only for it.

**Comment by wnitz** [comment]
@mmarkeloff, I have a commit ready for this issue too.
Do you want me to create another pull request or to commit directly to this repository?

**Comment by mmarkeloff** [comment]
@wnitz You are free to choose. Anyway i will see the diffs.
